name: Full mirror of Keiyoushi repo (no NSFW)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Clone official repo
        run: |
          rm -rf upstream
          git clone --depth=1 https://github.com/keiyoushi/extensions.git upstream

      - name: Copy repo folder
        run: |
          rm -rf repo
          cp -r upstream/repo repo

      - name: Remove NSFW from indexes
        run: |
          jq '[.[] | select(.nsfw != 1)]' repo/index.json > repo/index.tmp.json
          jq -c '[.[] | select(.nsfw != 1)]' repo/index.min.json > repo/index.tmp.min.json
          mv repo/index.tmp.json repo/index.json
          mv repo/index.tmp.min.json repo/index.min.json

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add repo
          git commit -m "Full mirror without NSFW" || exit 0
          git push
